rails-fakeflix-admin-base/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :movies
    resources :series
    resources :rentals
  end

  root 'home#index'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
end

rails-fakeflix-admin-base/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails-fakeflix-admin-base/app/models/episode.rb
class Episode < ApplicationRecord
  belongs_to :serie
end

rails-fakeflix-admin-base/app/models/movie.rb
class Movie < ApplicationRecord
  has_many :rentals, as: :rentable
  enum status: ["billboard", "preorder", "coming-soon" ]
end

rails-fakeflix-admin-base/app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :rentable, polymorphic: true
end

rails-fakeflix-admin-base/app/models/serie.rb
class Serie < ApplicationRecord
  has_many :rentals, as: :rentable
  has_many :episodes, dependent: :delete_all
  enum status: ["billboard", "preorder", "coming-soon" ]
end

rails-fakeflix-admin-base/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  devise :omniauthable, omniauth_providers: %i[facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end

  def regular?
    self.role == "regular"
  end

  def admin?
    self.role == "admin"
  end

end

rails-fakeflix-admin-base/app/controllers/admin/movies_controller.rb
class Admin::MoviesController < ApplicationController
  before_action :authoriza_admin, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  def index
    @movies = Movie.all
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @movies}
    end
  end

  def new
    @movie = Movie.new
  end

  def edit
  end

  def show
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to admin_movie_path(@movie), notice: 'movie was successfully created.'
    else
      render :new
    end
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update(movie_params)
      redirect_to admin_movie_path(@movie), notice: 'movie was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @movie.destroy
    redirect_to admin_movies_path, notice: 'Movie was successfully destroyed.'
  end

  private
  def set_movie
    @movie = Movie.find(params[:id])
  end

  def movie_params
    params.require(:movie).permit(:title ,:description ,:rating ,:duration ,:price ,:status ,:progress)
  end

  def authoriza_admin
    authorize Movie
  end
end

rails-fakeflix-admin-base/app/controllers/admin/rentals_controller.rb
class Admin::RentalsController < ApplicationController
  before_action :set_rental, only: [:show, :edit, :update, :destroy]

  def index
    @rentals = Rental.all
  end

  def new
    @rental = Rental.new
  end

  def edit
  end
  
  def show
  end

  
  def create
    @rental = Rental.new(rental_params)
    if @rental.save
      redirect_to admin_rental_path(@rental), notice: 'Serie was successfully created.'
    else
      render :new
    end
  end

  def update
    @rental = Rental.find(params[:id])
    if @rental.update(rental_params)
      redirect_to admin_rental_path(@rental), notice: 'Serie was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @rental.destroy
    redirect_to admin_rentals_path, notice: 'Serie was successfully destroyed.'
  end

  private
  def set_rental
    @rental = Rental.find(params[:id])
  end

  def rental_params
    params.require(:rental).permit(:paid_price, :rentable_type, :rentable_id)
  end
end

rails-fakeflix-admin-base/app/controllers/admin/series_controller.rb
class Admin::SeriesController < ApplicationController
  before_action :set_serie, only: [:show, :edit, :update, :destroy]

  def index
    @series = Serie.all
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @series}
    end
  end

  def new
    @serie = Serie.new
  end

  def edit
  end
  
  def show
  end

  
  def create
    @serie = Serie.new(serie_params)
    if @serie.save
      redirect_to admin_series_path(@serie), notice: 'Serie was successfully created.'
    else
      render :new
    end
  end

  def update
    @serie = Serie.find(params[:id])
    if @serie.update(serie_params)
      redirect_to admin_series_path(@serie), notice: 'Serie was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @serie.destroy
    redirect_to admin_series_index_path, notice: 'Serie was successfully destroyed.'
  end

  private
  def set_serie
    @serie = Serie.find(params[:id])
  end

  def serie_params
    params.require(:serie).permit(:title ,:description ,:rating , :price ,:status)
  end
end

rails-fakeflix-admin-base/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  before_action :authenticate_user!, except: [:index, :show]
  before_action :configure_permitted_parameters, if: :devise_controller?
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:role, :email, :password)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:role, :email, :password, :current_password)}
  end

  private

  def user_not_authorized
    flash[:alert] = "Youy are not authorized to perform this action"
    redirect_to root_path
  end

end

rails-fakeflix-admin-base/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

rails-fakeflix-admin-base/app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
end

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user
      sign_in_and_redirect @user
      set_flash_message(:notice, :success, kind: "Facebook")
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

rails-fakeflix-admin-base/app/helpers/application_helper.rb
module ApplicationHelper
end

rails-fakeflix-admin-base/app/views/admin/movies/_form.html.erb
<%= form_for [:admin, @movie] do |f| %>c
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @movie.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :rating %>
    <%= f.text_field :rating %>
  </div>

  <div class="field">
    <%= f.label :duration %>
    <%= f.text_field :duration %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.select :status, ["coming-soon", "preorder", "billboard"] %>
  </div>

  <div class="field">
    <%= f.label :progress %>
    <%= f.text_field :progress %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails-fakeflix-admin-base/app/views/admin/movies/edit.html.erb
<h1>Edit Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', admin_movies_path %>

rails-fakeflix-admin-base/app/views/admin/movies/index.html.erb
<div>
  <h2>List movies</h2>
  <%= link_to 'New movie', new_admin_movie_path %>
</div>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Rating</th>
      <th>Duration</th>
      <th>Price</th>
      <th>Status</th>
      <th>Progress</th>
      <th>Show</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @movies.each do |movie|%>
        <tr>
          <td><%= movie.title %></td>
          <td><%= movie.description %></td>
          <td><%= movie.rating %></td>
          <td><%= movie.duration %></td>
          <td><%= movie.price %></td>
          <td><%= movie.status %></td>
          <td><%= movie.progress %></td>
          <td><%= link_to 'Show', admin_movie_path(movie) %></td>
          <td>
            <%= link_to 'Edit', edit_admin_movie_path(movie) %>
            <%= link_to 'Destroy', admin_movie_path(movie), method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
  </tbody>
</table>

rails-fakeflix-admin-base/app/views/admin/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', admin_movies_path %>

rails-fakeflix-admin-base/app/views/admin/movies/show.html.erb
<h2><%= @movie.title %></h2>
<div>
  <p><b>Description:</b> <%= @movie.description %></p>
  <p><b>Rating:</b> <%= @movie.rating %></p>
  <p><b>Duration:</b> <%= @movie.duration %></p>
  <p><b>Price:</b> <%= @movie.price %></p>
  <p><b>Status:</b> <%= @movie.status %></p>
  <p><b>Progress:</b> <%= @movie.progress %></p>
</div>
<%= link_to 'Back', admin_movies_path %>

rails-fakeflix-admin-base/app/views/admin/rentals/_form.html.erb
<%= form_for [:admin, @rental] do |f| %>
  <% if @rental.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @rental.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :paid_price %>
    <%= f.text_field :paid_price %>
  </div>

  <div class="field">
    <label for="rentable_type">Select Type</label>
    <select id="rentable_type" name="rental[rentable_type]">
      <%= options_for_select(['Movie', 'Serie']) %>
    </select>
  </div>

  <div class="field">
    <%= f.label :rentable_id %>
    <%= f.collection_select :rentable_id, Movie.all, :id, :title %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script>
  typeSelect = document.getElementById("rentable_type");
  rentableSelect = document.getElementById("rental_rentable_id")
  typeSelect.addEventListener("change", (e) => {
    let resource =  e.target.value === 'Movie' ? 'movies' : 'series'
    fetch(`/admin/${resource}.json`)
      .then(response => {
        return response.json();
      })
      .then(data => {
        let html = '';
        data.forEach(rentable => {
          html += `
            <option value="${rentable.id}">${rentable.title}</option>
          `
        })
        rentableSelect.innerHTML = html
      });
  })
</script>

rails-fakeflix-admin-base/app/views/admin/rentals/edit.html.erb
<h1>Edit Rental</h1>

<%= render 'form', rental: @rental %>

<%= link_to 'Back', admin_rentals_path %>

rails-fakeflix-admin-base/app/views/admin/rentals/index.html.erb
<div>
  <h2>List rentals</h2>
  <%= link_to 'New rental', new_admin_rental_path %>
</div>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Precio</th>
      <th>Type</th>
      <th>Rentable</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @rentals.each do |rental|%>
        <tr>
          <td><%= rental.id %></td>
          <td><%= rental.paid_price %></td>
          <td><%= rental.rentable_type %></td>
          <td><%= rental.rentable.title %></td>
          <td>
            <%= link_to 'Edit', edit_admin_rental_path(rental) %>
            <%= link_to 'Destroy', admin_rental_path(rental), method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
  </tbody>
</table>

rails-fakeflix-admin-base/app/views/admin/rentals/new.html.erb
<h1>New Rental</h1>

<%= render 'form', rental: @rental %>

<%= link_to 'Back', admin_rentals_path %>

rails-fakeflix-admin-base/app/views/admin/rentals/show.html.erb
<h2>Rental #<%= @rental.id %></h2>
<div>
  <p><b>Rentable:</b> <%= @rental.rentable.title %></p>
  <p><b>Price:</b> <%= @rental.paid_price %></p>
</div>
<%= link_to 'Back', admin_rentals_path %>

rails-fakeflix-admin-base/app/views/admin/series/_form.html.erb
<%= form_for @serie, :url => url  do |f| %>
  <% if @serie.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @serie.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :rating %>
    <%= f.text_field :rating %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.select :status, ["coming-soon", "preorder", "billboard"] %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails-fakeflix-admin-base/app/views/admin/series/edit.html.erb
<h1>Edit Serie</h1>

<%= render 'form', serie: @serie, url: admin_series_path(@serie)  %>

<%= link_to 'Back', admin_series_index_path %>

rails-fakeflix-admin-base/app/views/admin/series/index.html.erb
<div>
  <h2>List series</h2>
  <%= link_to 'New serie', new_admin_series_path %>
</div>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Rating</th>
      <th>Price</th>
      <th>Status</th>
      <th>Show</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @series.each do |serie|%>
        <tr>
          <td><%= serie.title %></td>
          <td><%= serie.description %></td>
          <td><%= serie.rating %></td>
          <td><%= serie.price %></td>
          <td><%= serie.status %></td>
          <td><%= link_to 'Show', admin_series_path(serie) %></td>
          <td>
            <%= link_to 'Edit', edit_admin_series_path(serie) %>
            <%= link_to 'Destroy', admin_series_path(serie), method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
  </tbody>
</table>

rails-fakeflix-admin-base/app/views/admin/series/new.html.erb
<h1>New Serie</h1>

<%= render 'form', serie: @serie, url: admin_series_index_path  %>

<%= link_to 'Back', admin_series_index_path %>

rails-fakeflix-admin-base/app/views/admin/series/show.html.erb
<h2><%= @serie.title %></h2>

<div>
  <p><b>Description:</b> <%= @serie.description %></p>
  <p><b>Rating:</b> <%= @serie.rating %></p>
  <p><b>Price:</b> <%= @serie.price %></p>
  <p><b>Status:</b> <%= @serie.status %></p>
</div>

<%= link_to 'Back', admin_series_index_path %>

rails-fakeflix-admin-base/app/views/home/index.html.erb
<h1>Welcome Admin</h1>

rails-fakeflix-admin-base/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FakeflixAdmin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render '/partials/nav' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div>
      <% if current_user %>
        Has iniciado sesión como <strong><%= current_user.email %></strong>!
        <%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to 'Iniciar sesión', new_user_session_path %>
      <% end %>
    </div>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

rails-fakeflix-admin-base/app/views/partials/_nav.html.erb
<nav>
  <div class="container navbar">
    <div>
      <a href="/">MyApp</a>
    </div>
    <ul>
      <%= link_to "Movies", admin_movies_path %>
      <%= link_to "Series", admin_series_index_path %>
      <%= link_to "Rentals", admin_rentals_path %>
    </ul>

    <div>
      <a>Access with:</a>
      <%= link_to "Facebook", user_facebook_omniauth_authorize_path %>
    </div>
  </div>
</nav>